# Generated by Django 3.1.2 on 2020-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='year',
            field=models.IntegerField(choices=[(198485, '1984/85'), (198586, '1985/86'), (198687, '1986/87'), (198788, '1987/88'), (198889, '1988/89'), (198990, '1989/90'), (199091, '1990/91'), (199192, '1991/92'), (199293, '1992/93'), (199394, '1993/94'), (199495, '1994/95'), (199596, '1995/96'), (199697, '1996/97'), (199798, '1997/98'), (199899, '1998/99'), (19990, '1999/0'), (20001, '2000/1'), (20012, '2001/2'), (20023, '2002/3'), (20034, '2003/4'), (20045, '2004/5'), (20056, '2005/6'), (20067, '2006/7'), (20078, '2007/8'), (20089, '2008/9'), (200910, '2009/10'), (201011, '2010/11'), (201112, '2011/12'), (201213, '2012/13'), (201314, '2013/14'), (201415, '2014/15'), (201516, '2015/16'), (201617, '2016/17'), (201718, '2017/18'), (201819, '2018/19'), (201920, '2019/20'), (202021, '2020/21')]),
        ),
    ]
