# Generated by Django 3.1.2 on 2020-10-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20201008_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.IntegerField(),
        ),
    ]
