# Generated by Django 3.1.2 on 2020-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20201013_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='area',
            field=models.FloatField(),
        ),
    ]
