# Generated by Django 3.1.2 on 2020-11-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20201014_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_name', to='production.district'),
        ),
    ]
