# Generated by Django 3.1.2 on 2020-11-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20201110_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.crop'),
        ),
        migrations.AlterField(
            model_name='production',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.district'),
        ),
    ]
